apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kommander-traefik-kommander-ai
subjects:
- kind: ServiceAccount
  name: kommander-traefik
  namespace: kommander
roleRef:
  kind: ClusterRole
  name: kommander-traefik-kommander-ai
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kommander-traefik-kommander-ai
rules:
- apiGroups:
  - hub.traefik.io
  resources:
  - aiservices
  verbs:
  - list
  - watch
  - create
  - update
  - patch
  - delete
  - get